on: push

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate keystore
      id: generate_keystore
      env:
        SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.SECRET_RELEASE_KEYSTORE_BASE64 }}
      run: |
        echo $SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > ./release.keystore
        
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: 3.9

    - name: Populate export_presets
      id: populate_export_presets
      env:
        SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.SECRET_RELEASE_KEYSTORE_USER }}
        SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.SECRET_RELEASE_KEYSTORE_PASSWORD }}
      run: |
        python ./Deploy/populate_keystore.py ./export_presets.cfg ./release.keystore $SECRET_RELEASE_KEYSTORE_USER $SECRET_RELEASE_KEYSTORE_PASSWORD

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v4.1.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.5-stable/Godot_v3.5-stable_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.5-stable/Godot_v3.5-stable_mono_export_templates.tpz
        relative_project_path: ./
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Android
        path: /home/runner/.local/share/godot/builds/Android/*
        if-no-files-found: error

    - name: Set up Butler
      run: |
        mkdir -p ~/.local/share/butler
        cd ~/.local/share/butler
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x ./butler
        ./butler -V
    
    - name: Itch.io Upload
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_CREDS }}
        BUTLER_USER: ${{ secrets.BUTLER_USER }}
        GAME_ID: commission-tracker
        CHANNEL: android
      run: |
        export_dir=~/.local/share/godot/builds/Android
        
        ls $export_dir
        ~/.local/share/butler/butler push $export_dir $BUTLER_USER/$GAME_ID:$CHANNEL
