# Whenever a tag push matching pattern "v*" then run the job
on: push

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Export Game
    steps:
      # Always include the checkout step so that
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v3
      # Ensure that you get the entire project history
      with:
        fetch-depth: 0

    - name: Generate keystore
      id: generate_keystore
      env:
        SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.SECRET_RELEASE_KEYSTORE_BASE64 }}
      run: |
        cd /home/runner/work/CommissionTracker/CommissionTracker
        echo $SECRET_RELEASE_KEYSTORE_BASE64 | base64 --decode > ./release.keystore

    - name: Populate export_presets
      id: populate_export_presets
      with:
        python-version: 3.10
      env:
        SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.SECRET_RELEASE_KEYSTORE_USER }}
        SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.SECRET_RELEASE_KEYSTORE_PASSWORD }}
      run: |
        cd /home/runner/work/CommissionTracker/CommissionTracker
        python ./Deploy/populate_keystore.py "./release.keystore" $SECRET_RELEASE_KEYSTORE_USER $SECRET_RELEASE_KEYSTORE_PASSWORD

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v4.1.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.5-stable/Godot_v3.5-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.5-stable/Godot_v3.5-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
